"""initial schema

Revision ID: a1146605e2b4
Revises: 
Create Date: 2026-04-14 23:53:41.341197

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1146605e2b4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bids', sa.JSON(), nullable=False),
    sa.Column('asks', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'snapshot_at', name='uq_books_token_snap')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_snapshot_at'), ['snapshot_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_token_id'), ['token_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)

    op.create_table('halt_flags',
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('halted', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bot_id')
    )
    op.create_table('markets',
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fee_rate_bps', sa.Integer(), nullable=True),
    sa.Column('yes_token_id', sa.String(), nullable=True),
    sa.Column('no_token_id', sa.String(), nullable=True),
    sa.Column('is_neg_risk', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('size', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('pnl_snapshots',
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('realised_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unrealised_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('open_exposure_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('drawdown_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('bot_id', 'snapshot_date')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_basis_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_condition_id'), ['condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_status'), ['status'], unique=False)

    op.create_table('price_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ancillary_decoded', sa.String(), nullable=True),
    sa.Column('resolved_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('is_resolved', sa.Integer(), nullable=False),
    sa.Column('dispute_count', sa.Integer(), nullable=False),
    sa.Column('final_outcome', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispute_risk', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('claude_pick', sa.String(), nullable=True),
    sa.Column('claude_confidence', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('claude_implied_prob', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('resolution_prediction', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_condition_id'), ['condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_scored_at'), ['scored_at'], unique=False)

    op.create_table('trades',
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fee_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usd_gbp_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('gbp_notional', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_bot_id'), ['bot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_bot_id'))

    op.drop_table('trades')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_scored_at'))
        batch_op.drop_index(batch_op.f('ix_scores_condition_id'))

    op.drop_table('scores')
    op.drop_table('price_requests')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_status'))
        batch_op.drop_index(batch_op.f('ix_positions_condition_id'))
        batch_op.drop_index(batch_op.f('ix_positions_bot_id'))

    op.drop_table('positions')
    op.drop_table('pnl_snapshots')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_bot_id'))

    op.drop_table('orders')
    op.drop_table('markets')
    op.drop_table('halt_flags')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_events_bot_id'))

    op.drop_table('events')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_token_id'))
        batch_op.drop_index(batch_op.f('ix_books_snapshot_at'))

    op.drop_table('books')
    # ### end Alembic commands ###
