"""add volume_24h_usd to markets

Revision ID: 2a92772f19ea
Revises: a1146605e2b4
Create Date: 2026-04-15 00:45:41.337934

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a92772f19ea'
down_revision: str | None = 'a1146605e2b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # SQLite cannot add a NOT NULL column without a default to a populated
    # table. server_default='0' backfills existing rows (markets without
    # recorded volume should not pass min-volume filters anyway). New rows
    # continue to require an explicit value from the application layer.
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'volume_24h_usd',
                sa.Numeric(precision=18, scale=2),
                nullable=False,
                server_default='0',
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('volume_24h_usd')

    # ### end Alembic commands ###
